"""
Inter-annotator agreement between annotator 1 and annotator 2 (simulated) sheets.

Loads completed annotation CSVs, aligns on ``id``, and reports percent agreement,
Cohen's Kappa, bootstrap 95% CI, confusion matrix, per-class agreement, and
writes ``reports/kappa_report.md``.

Usage (from project root):

    python calculate_kappa.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import cohen_kappa_score, confusion_matrix

PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from reports._common import dataframe_to_markdown, ensure_reports_dir

ANNOTATOR1_PATH = PROJECT_ROOT / "dataset" / "annotations" / "annotator1_completed_final.csv"
ANNOTATOR2_PATH = PROJECT_ROOT / "dataset" / "annotations" / "annotator2_completed.csv"
FIGURE_PATH = PROJECT_ROOT / "reports" / "kappa_confusion_matrix.png"
REPORT_PATH = PROJECT_ROOT / "reports" / "kappa_report.md"
DISAGREEMENT_CSV = PROJECT_ROOT / "reports" / "disagreement_examples.csv"

LABELS = ["Pratyaksha", "Anumana", "Upamana", "Shabda"]
BOOTSTRAP_SAMPLES = 1000
BOOTSTRAP_SEED = 42

DISAGREEMENT_REASONS: dict[tuple[str, str], str] = {
    ("Pratyaksha", "Anumana"): "Perceptual or measurement language overlaps with inferential/causal framing.",
    ("Pratyaksha", "Shabda"): "Testimonial or authority wording co-occurs with direct-observation cues.",
    ("Anumana", "Pratyaksha"): "Inferential connector present but span also reads as direct report.",
    ("Upamana", "Anumana"): "Comparative structure is subtle; span functions as general inference.",
    ("Upamana", "Shabda"): "Analogy cues overlap with cited authority or reported claim.",
    ("Shabda", "Anumana"): "Authority or source implicit; span reads as reason-giving rather than testimony.",
    ("Shabda", "Upamana"): "Reported claim uses comparative phrasing suggestive of analogy.",
}


def interpret_kappa(kappa: float) -> str:
    if kappa < 0.4:
        return "weak agreement"
    if kappa < 0.6:
        return "moderate agreement"
    if kappa < 0.8:
        return "substantial agreement"
    return "strong agreement"


def per_class_agreement(a1: pd.Series, a2: pd.Series) -> pd.DataFrame:
    """Per-label counts and agreement rates."""
    rows = []
    n = len(a1)
    for label in LABELS:
        m1 = a1 == label
        m2 = a2 == label
        both = (m1 & m2).sum()
        c1 = int(m1.sum())
        c2 = int(m2.sum())
        either = int((m1 | m2).sum())
        rows.append(
            {
                "pramana_label": label,
                "both_agree": int(both),
                "annotator1_count": c1,
                "annotator2_count": c2,
                "pct_of_total_both_agree": round(100.0 * both / n, 2) if n else 0.0,
                "agreement_when_annotator1_label": round(100.0 * both / c1, 2) if c1 else None,
                "agreement_when_annotator2_label": round(100.0 * both / c2, 2) if c2 else None,
                "agreement_when_either_label": round(100.0 * both / either, 2) if either else None,
            }
        )
    return pd.DataFrame(rows)


def bootstrap_kappa_ci(
    y1: pd.Series,
    y2: pd.Series,
    n_samples: int = BOOTSTRAP_SAMPLES,
    seed: int = BOOTSTRAP_SEED,
) -> tuple[float, float, float]:
    """Return (point_estimate, ci_low, ci_high) for Cohen's kappa via bootstrap."""
    rng = np.random.default_rng(seed)
    n = len(y1)
    y1_arr = y1.to_numpy()
    y2_arr = y2.to_numpy()
    kappas: list[float] = []
    for _ in range(n_samples):
        idx = rng.integers(0, n, size=n)
        k = cohen_kappa_score(y1_arr[idx], y2_arr[idx], labels=LABELS)
        kappas.append(float(k))
    low, high = np.percentile(kappas, [2.5, 97.5])
    point = float(cohen_kappa_score(y1, y2, labels=LABELS))
    return point, float(low), float(high)


def write_kappa_report(
    n: int,
    agreements: int,
    disagreements: int,
    agreement_pct: float,
    kappa: float,
    ci_low: float,
    ci_high: float,
    cm_df: pd.DataFrame,
    stats: pd.DataFrame,
) -> None:
    ensure_reports_dir()
    lines: list[str] = []
    lines.append("# InferAI — Inter-Annotator Agreement (Kappa) Report\n\n")
    lines.append(
        "Agreement statistics between annotator 1 and annotator 2 on the shared annotation "
        "corpus. Generated by `calculate_kappa.py`.\n\n"
    )

    lines.append("## Summary\n\n")
    summary = pd.DataFrame(
        [
            {"Metric": "Matched examples", "Value": n},
            {"Metric": "Agreements", "Value": agreements},
            {"Metric": "Disagreements", "Value": disagreements},
            {"Metric": "Agreement percentage", "Value": f"{agreement_pct:.2f}%"},
            {"Metric": "Cohen's Kappa", "Value": round(kappa, 4)},
            {"Metric": "Bootstrap 95% CI (kappa)", "Value": f"[{ci_low:.4f}, {ci_high:.4f}]"},
            {"Metric": "Interpretation", "Value": interpret_kappa(kappa)},
        ]
    )
    lines.append(dataframe_to_markdown(summary) + "\n\n")

    lines.append("## Confusion matrix (rows = annotator 1, columns = annotator 2)\n\n")
    lines.append(dataframe_to_markdown(cm_df.reset_index().rename(columns={"index": "Annotator1"})) + "\n\n")
    lines.append("![Kappa confusion matrix](kappa_confusion_matrix.png)\n\n")

    lines.append("## Per-class agreement rates\n\n")
    lines.append(dataframe_to_markdown(stats) + "\n\n")

    lines.append("## Interpretation\n\n")
    lines.append(
        f"Cohen's κ = **{kappa:.4f}** ({interpret_kappa(kappa)}) with **{agreement_pct:.1f}%** "
        f"raw agreement. The bootstrap 95% CI [{ci_low:.4f}, {ci_high:.4f}] indicates "
        "stable agreement at the corpus scale.\n\n"
        "**Caveat:** annotator 2 labels were partly rule-assisted (`auto_annotate_second_annotator.py`), "
        "so κ reflects consistency with a similar heuristic rather than fully independent human "
        "judgment. For publication, independent blind annotation is recommended.\n"
    )

    REPORT_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"Report saved: {REPORT_PATH}")


def per_class_disagreement(a1: pd.Series, a2: pd.Series) -> pd.DataFrame:
    """Count disagreements where annotator 1 assigned each label."""
    rows = []
    for label in LABELS:
        mask = a1 == label
        n = int(mask.sum())
        disagree = int((mask & (a1 != a2)).sum())
        rows.append(
            {
                "pramana_label": label,
                "annotator1_assignments": n,
                "disagreements": disagree,
                "disagreement_rate_pct": round(100.0 * disagree / n, 2) if n else 0.0,
            }
        )
    return pd.DataFrame(rows)


def disagreement_reason(a1: str, a2: str) -> str:
    return DISAGREEMENT_REASONS.get(
        (a1, a2),
        f"Boundary disagreement between {a1} and {a2} on short argumentative span.",
    )


def write_disagreement_examples(merged: pd.DataFrame) -> pd.DataFrame:
    """Export rows where annotators disagree."""
    text_col = "text" if "text" in merged.columns else None
    rows = []
    for _, row in merged.iterrows():
        a1 = str(row["pramana_label_a1"]).strip()
        a2 = str(row["pramana_label_a2"]).strip()
        if a1 == a2:
            continue
        rows.append(
            {
                "text": row[text_col] if text_col else "",
                "annotator_1": a1,
                "annotator_2": a2,
                "final_label": a1,
                "reason_for_disagreement": disagreement_reason(a1, a2),
            }
        )
    out = pd.DataFrame(rows)
    DISAGREEMENT_CSV.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(DISAGREEMENT_CSV, index=False)
    print(f"Disagreement examples saved: {DISAGREEMENT_CSV}")
    return out


def append_extended_kappa_section(
    *,
    agreement_pct: float,
    kappa: float,
    ci_low: float,
    ci_high: float,
    stats: pd.DataFrame,
    disagree_stats: pd.DataFrame,
    cm_df: pd.DataFrame,
    n_disagreements: int,
) -> None:
    """Append extended analysis without removing existing report content."""
    marker = "## Extended Annotation Analysis"
    existing = REPORT_PATH.read_text(encoding="utf-8") if REPORT_PATH.is_file() else ""
    if marker in existing:
        base = existing.split(marker)[0].rstrip() + "\n\n"
    else:
        base = existing.rstrip() + "\n\n"

    lines: list[str] = [base, f"{marker}\n\n"]
    lines.append(
        "Extended inter-annotator diagnostics appended by `calculate_kappa.py`. "
        "The summary statistics in the sections above are unchanged.\n\n"
    )

    lines.append("### Agreement metrics\n\n")
    lines.append("| Metric | Value |\n|--------|------:|\n")
    lines.append(f"| Agreement % | {agreement_pct:.2f}% |\n")
    lines.append(f"| Cohen's Kappa | {kappa:.4f} |\n")
    lines.append(f"| Bootstrap 95% CI | [{ci_low:.4f}, {ci_high:.4f}] |\n\n")

    lines.append("### Per-class agreement\n\n")
    lines.append(dataframe_to_markdown(stats) + "\n\n")

    lines.append("### Per-class disagreement\n\n")
    lines.append(dataframe_to_markdown(disagree_stats) + "\n\n")

    lines.append("### Confusion matrix explanation\n\n")
    lines.append(
        "Rows correspond to **annotator 1** labels; columns correspond to **annotator 2** labels. "
        "Diagonal cells are agreements; off-diagonal cells are disagreements. "
        f"The matrix accounts for all **{int(cm_df.values.sum())}** matched examples "
        f"({n_disagreements} off-diagonal assignments).\n\n"
    )
    lines.append(dataframe_to_markdown(cm_df.reset_index().rename(columns={"index": "Annotator1"})) + "\n\n")

    lines.append("Primary disagreement patterns:\n\n")
    for a1 in LABELS:
        for a2 in LABELS:
            if a1 != a2 and cm_df.loc[a1, a2] > 0:
                lines.append(
                    f"- **{a1} → {a2}:** {int(cm_df.loc[a1, a2])} case(s) — "
                    f"{disagreement_reason(a1, a2)}\n"
                )

    lines.append(
        f"\n### Disagreement examples\n\n"
        f"All **{n_disagreements}** disagreement rows are exported to "
        f"`reports/disagreement_examples.csv` with annotator labels and heuristic "
        f"disagreement reasons.\n"
    )

    REPORT_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"Extended section appended: {REPORT_PATH}")


def main() -> None:
    for path in (ANNOTATOR1_PATH, ANNOTATOR2_PATH):
        if not path.is_file():
            raise FileNotFoundError(f"Missing file: {path}")

    df1 = pd.read_csv(ANNOTATOR1_PATH)
    df2 = pd.read_csv(ANNOTATOR2_PATH)

    for name, df in ("annotator1", df1), ("annotator2", df2):
        if "id" not in df.columns or "pramana_label" not in df.columns:
            raise ValueError(f"{name} CSV must contain id and pramana_label")

    merged = df1[["id", "text", "pramana_label"]].merge(
        df2[["id", "pramana_label"]],
        on="id",
        how="inner",
        suffixes=("_a1", "_a2"),
    )

    if len(merged) != len(df1) or len(merged) != len(df2):
        raise ValueError(
            "ID mismatch between annotators: "
            f"a1={len(df1)}, a2={len(df2)}, merged={len(merged)}"
        )

    y1 = merged["pramana_label_a1"].astype(str).str.strip()
    y2 = merged["pramana_label_a2"].astype(str).str.strip()

    invalid = set(y1.unique()) | set(y2.unique())
    invalid -= set(LABELS)
    if invalid:
        raise ValueError(f"Unexpected labels: {invalid}")

    n = len(merged)
    agreements = int((y1 == y2).sum())
    disagreements = n - agreements
    agreement_pct = 100.0 * agreements / n if n else 0.0
    kappa, ci_low, ci_high = bootstrap_kappa_ci(y1, y2)

    cm = confusion_matrix(y1, y2, labels=LABELS)

    print("=" * 60)
    print("Inter-annotator agreement (NyayaXAI / InferAI)")
    print("=" * 60)
    print(f"Total examples (matched on id): {n}")
    print(f"Agreements:   {agreements}")
    print(f"Disagreements: {disagreements}")
    print(f"Agreement percentage: {agreement_pct:.2f}%")
    print(f"Cohen's Kappa: {kappa:.4f}")
    print(f"Bootstrap 95% CI: [{ci_low:.4f}, {ci_high:.4f}]")
    print(f"Interpretation: {interpret_kappa(kappa)}")
    print()

    print("Confusion matrix (rows = annotator 1, columns = annotator 2):")
    cm_df = pd.DataFrame(cm, index=LABELS, columns=LABELS)
    print(cm_df.to_string())
    print()

    print("Per-class agreement statistics:")
    stats = per_class_agreement(y1, y2)
    print(stats.to_string(index=False))
    print()

    # Plot
    FIGURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    plt.figure(figsize=(7, 5.5))
    sns.heatmap(
        cm_df,
        annot=True,
        fmt="d",
        cmap="Greens",
        cbar_kws={"label": "Count"},
        linewidths=0.5,
        linecolor="white",
    )
    plt.xlabel("Annotator 2")
    plt.ylabel("Annotator 1")
    plt.title(f"Confusion matrix (κ = {kappa:.3f}, agreement = {agreement_pct:.1f}%)")
    plt.tight_layout()
    plt.savefig(FIGURE_PATH, dpi=150)
    plt.close()

    print(f"Figure saved: {FIGURE_PATH}")

    write_kappa_report(
        n=n,
        agreements=agreements,
        disagreements=disagreements,
        agreement_pct=agreement_pct,
        kappa=kappa,
        ci_low=ci_low,
        ci_high=ci_high,
        cm_df=cm_df,
        stats=stats,
    )

    disagree_stats = per_class_disagreement(y1, y2)
    write_disagreement_examples(merged)
    append_extended_kappa_section(
        agreement_pct=agreement_pct,
        kappa=kappa,
        ci_low=ci_low,
        ci_high=ci_high,
        stats=stats,
        disagree_stats=disagree_stats,
        cm_df=cm_df,
        n_disagreements=disagreements,
    )


if __name__ == "__main__":
    main()
