"""
Inter-annotator agreement between annotator 1 and annotator 2 (simulated) sheets.

Loads completed annotation CSVs, aligns on ``id``, and reports percent agreement,
Cohen's Kappa, bootstrap 95% CI, confusion matrix, per-class agreement, and
writes ``reports/kappa_report.md``.

Usage (from project root):

    python calculate_kappa.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import cohen_kappa_score, confusion_matrix

PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from reports._common import dataframe_to_markdown, ensure_reports_dir

ANNOTATOR1_PATH = PROJECT_ROOT / "dataset" / "annotations" / "annotator1_completed_final.csv"
ANNOTATOR2_PATH = PROJECT_ROOT / "dataset" / "annotations" / "annotator2_completed.csv"
FIGURE_PATH = PROJECT_ROOT / "reports" / "kappa_confusion_matrix.png"
REPORT_PATH = PROJECT_ROOT / "reports" / "kappa_report.md"

LABELS = ["Pratyaksha", "Anumana", "Upamana", "Shabda"]
BOOTSTRAP_SAMPLES = 1000
BOOTSTRAP_SEED = 42


def interpret_kappa(kappa: float) -> str:
    if kappa < 0.4:
        return "weak agreement"
    if kappa < 0.6:
        return "moderate agreement"
    if kappa < 0.8:
        return "substantial agreement"
    return "strong agreement"


def per_class_agreement(a1: pd.Series, a2: pd.Series) -> pd.DataFrame:
    """Per-label counts and agreement rates."""
    rows = []
    n = len(a1)
    for label in LABELS:
        m1 = a1 == label
        m2 = a2 == label
        both = (m1 & m2).sum()
        c1 = int(m1.sum())
        c2 = int(m2.sum())
        either = int((m1 | m2).sum())
        rows.append(
            {
                "pramana_label": label,
                "both_agree": int(both),
                "annotator1_count": c1,
                "annotator2_count": c2,
                "pct_of_total_both_agree": round(100.0 * both / n, 2) if n else 0.0,
                "agreement_when_annotator1_label": round(100.0 * both / c1, 2) if c1 else None,
                "agreement_when_annotator2_label": round(100.0 * both / c2, 2) if c2 else None,
                "agreement_when_either_label": round(100.0 * both / either, 2) if either else None,
            }
        )
    return pd.DataFrame(rows)


def bootstrap_kappa_ci(
    y1: pd.Series,
    y2: pd.Series,
    n_samples: int = BOOTSTRAP_SAMPLES,
    seed: int = BOOTSTRAP_SEED,
) -> tuple[float, float, float]:
    """Return (point_estimate, ci_low, ci_high) for Cohen's kappa via bootstrap."""
    rng = np.random.default_rng(seed)
    n = len(y1)
    y1_arr = y1.to_numpy()
    y2_arr = y2.to_numpy()
    kappas: list[float] = []
    for _ in range(n_samples):
        idx = rng.integers(0, n, size=n)
        k = cohen_kappa_score(y1_arr[idx], y2_arr[idx], labels=LABELS)
        kappas.append(float(k))
    low, high = np.percentile(kappas, [2.5, 97.5])
    point = float(cohen_kappa_score(y1, y2, labels=LABELS))
    return point, float(low), float(high)


def write_kappa_report(
    n: int,
    agreements: int,
    disagreements: int,
    agreement_pct: float,
    kappa: float,
    ci_low: float,
    ci_high: float,
    cm_df: pd.DataFrame,
    stats: pd.DataFrame,
) -> None:
    ensure_reports_dir()
    lines: list[str] = []
    lines.append("# InferAI — Inter-Annotator Agreement (Kappa) Report\n\n")
    lines.append(
        "Agreement statistics between annotator 1 and annotator 2 on the shared annotation "
        "corpus. Generated by `calculate_kappa.py`.\n\n"
    )

    lines.append("## Summary\n\n")
    summary = pd.DataFrame(
        [
            {"Metric": "Matched examples", "Value": n},
            {"Metric": "Agreements", "Value": agreements},
            {"Metric": "Disagreements", "Value": disagreements},
            {"Metric": "Agreement percentage", "Value": f"{agreement_pct:.2f}%"},
            {"Metric": "Cohen's Kappa", "Value": round(kappa, 4)},
            {"Metric": "Bootstrap 95% CI (kappa)", "Value": f"[{ci_low:.4f}, {ci_high:.4f}]"},
            {"Metric": "Interpretation", "Value": interpret_kappa(kappa)},
        ]
    )
    lines.append(dataframe_to_markdown(summary) + "\n\n")

    lines.append("## Confusion matrix (rows = annotator 1, columns = annotator 2)\n\n")
    lines.append(dataframe_to_markdown(cm_df.reset_index().rename(columns={"index": "Annotator1"})) + "\n\n")
    lines.append("![Kappa confusion matrix](kappa_confusion_matrix.png)\n\n")

    lines.append("## Per-class agreement rates\n\n")
    lines.append(dataframe_to_markdown(stats) + "\n\n")

    lines.append("## Interpretation\n\n")
    lines.append(
        f"Cohen's κ = **{kappa:.4f}** ({interpret_kappa(kappa)}) with **{agreement_pct:.1f}%** "
        f"raw agreement. The bootstrap 95% CI [{ci_low:.4f}, {ci_high:.4f}] indicates "
        "stable agreement at the corpus scale.\n\n"
        "**Caveat:** annotator 2 labels were partly rule-assisted (`auto_annotate_second_annotator.py`), "
        "so κ reflects consistency with a similar heuristic rather than fully independent human "
        "judgment. For publication, independent blind annotation is recommended.\n"
    )

    REPORT_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"Report saved: {REPORT_PATH}")


def main() -> None:
    for path in (ANNOTATOR1_PATH, ANNOTATOR2_PATH):
        if not path.is_file():
            raise FileNotFoundError(f"Missing file: {path}")

    df1 = pd.read_csv(ANNOTATOR1_PATH)
    df2 = pd.read_csv(ANNOTATOR2_PATH)

    for name, df in ("annotator1", df1), ("annotator2", df2):
        if "id" not in df.columns or "pramana_label" not in df.columns:
            raise ValueError(f"{name} CSV must contain id and pramana_label")

    merged = df1[["id", "pramana_label"]].merge(
        df2[["id", "pramana_label"]],
        on="id",
        how="inner",
        suffixes=("_a1", "_a2"),
    )

    if len(merged) != len(df1) or len(merged) != len(df2):
        raise ValueError(
            "ID mismatch between annotators: "
            f"a1={len(df1)}, a2={len(df2)}, merged={len(merged)}"
        )

    y1 = merged["pramana_label_a1"].astype(str).str.strip()
    y2 = merged["pramana_label_a2"].astype(str).str.strip()

    invalid = set(y1.unique()) | set(y2.unique())
    invalid -= set(LABELS)
    if invalid:
        raise ValueError(f"Unexpected labels: {invalid}")

    n = len(merged)
    agreements = int((y1 == y2).sum())
    disagreements = n - agreements
    agreement_pct = 100.0 * agreements / n if n else 0.0
    kappa, ci_low, ci_high = bootstrap_kappa_ci(y1, y2)

    cm = confusion_matrix(y1, y2, labels=LABELS)

    print("=" * 60)
    print("Inter-annotator agreement (NyayaXAI / InferAI)")
    print("=" * 60)
    print(f"Total examples (matched on id): {n}")
    print(f"Agreements:   {agreements}")
    print(f"Disagreements: {disagreements}")
    print(f"Agreement percentage: {agreement_pct:.2f}%")
    print(f"Cohen's Kappa: {kappa:.4f}")
    print(f"Bootstrap 95% CI: [{ci_low:.4f}, {ci_high:.4f}]")
    print(f"Interpretation: {interpret_kappa(kappa)}")
    print()

    print("Confusion matrix (rows = annotator 1, columns = annotator 2):")
    cm_df = pd.DataFrame(cm, index=LABELS, columns=LABELS)
    print(cm_df.to_string())
    print()

    print("Per-class agreement statistics:")
    stats = per_class_agreement(y1, y2)
    print(stats.to_string(index=False))
    print()

    # Plot
    FIGURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    plt.figure(figsize=(7, 5.5))
    sns.heatmap(
        cm_df,
        annot=True,
        fmt="d",
        cmap="Greens",
        cbar_kws={"label": "Count"},
        linewidths=0.5,
        linecolor="white",
    )
    plt.xlabel("Annotator 2")
    plt.ylabel("Annotator 1")
    plt.title(f"Confusion matrix (κ = {kappa:.3f}, agreement = {agreement_pct:.1f}%)")
    plt.tight_layout()
    plt.savefig(FIGURE_PATH, dpi=150)
    plt.close()

    print(f"Figure saved: {FIGURE_PATH}")

    write_kappa_report(
        n=n,
        agreements=agreements,
        disagreements=disagreements,
        agreement_pct=agreement_pct,
        kappa=kappa,
        ci_low=ci_low,
        ci_high=ci_high,
        cm_df=cm_df,
        stats=stats,
    )


if __name__ == "__main__":
    main()
