"""
Automatic interpretation of the held-out test confusion matrix.

Outputs:
  - reports/confusion_matrix_analysis.md

Usage:
    python reports/generate_confusion_matrix_analysis.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from classification.embedder import generate_embeddings
from reports._common import dataframe_to_markdown, ensure_reports_dir

# Human-readable confusion explanations keyed by (true, pred) ordered pairs.
PAIR_EXPLANATIONS: dict[tuple[str, str], str] = {
    ("Anumana", "Upamana"): (
        "inferential cues (therefore, must follow) overlap with analogy-based phrasing "
        "(like, similar to, just as)."
    ),
    ("Upamana", "Anumana"): (
        "comparative analogies are read as causal or inferential chains."
    ),
    ("Pratyaksha", "Anumana"): (
        "direct perceptual reports are misread when hedging or inference markers appear nearby."
    ),
    ("Pratyaksha", "Shabda"): (
        "first-person observation blends with testimonial or authority language."
    ),
    ("Shabda", "Pratyaksha"): (
        "testimonial claims with sensory framing are classified as direct perception."
    ),
    ("Shabda", "Anumana"): (
        "authority-based assertions carry implicit inferential structure."
    ),
    ("Anumana", "Shabda"): (
        "inferential arguments cite experts or sources, blurring Anumana and Shabda."
    ),
    ("Upamana", "Shabda"): (
        "analogies referencing authoritative sources resemble Shabda testimony."
    ),
}


def _pair_explanation(true_lbl: str, pred_lbl: str) -> str:
    return PAIR_EXPLANATIONS.get(
        (true_lbl, pred_lbl),
        f"the model confuses rhetorical cues associated with {true_lbl} and {pred_lbl}.",
    )


def analyze_confusion_matrix(cm: np.ndarray, classes: list[str]) -> dict:
    n = len(classes)
    off_diag: list[dict] = []
    diag_recall: list[dict] = []

    for i, true_lbl in enumerate(classes):
        row_sum = int(cm[i].sum())
        recall = float(cm[i, i] / row_sum) if row_sum else 0.0
        diag_recall.append({"class": true_lbl, "recall": recall, "support": row_sum})

        for j, pred_lbl in enumerate(classes):
            if i == j:
                continue
            count = int(cm[i, j])
            if count > 0:
                off_diag.append(
                    {
                        "true": true_lbl,
                        "predicted": pred_lbl,
                        "count": count,
                        "rate_of_true_class": count / row_sum if row_sum else 0.0,
                    }
                )

    off_diag.sort(key=lambda x: x["count"], reverse=True)
    diag_recall.sort(key=lambda x: x["recall"])

    most_confused = off_diag[0] if off_diag else None
    least_confused = off_diag[-1] if off_diag else None
    lowest_recall = min(diag_recall, key=lambda x: x["recall"])
    highest_recall = max(diag_recall, key=lambda x: x["recall"])

    return {
        "off_diag": off_diag,
        "most_confused": most_confused,
        "least_confused": least_confused,
        "lowest_recall": lowest_recall,
        "highest_recall": highest_recall,
    }


def main() -> None:
    ensure_reports_dir()

    model = joblib.load(_ROOT / "models" / "nyaya_model.pkl")
    le = joblib.load(_ROOT / "models" / "label_encoder.pkl")
    tdf = pd.read_csv(_ROOT / "dataset" / "test_set.csv")

    texts = tdf["text"].astype(str).tolist()
    y_true = le.transform(tdf["pramana_label"].astype(str))
    X = generate_embeddings(texts)
    y_pred = model.predict(X)

    classes = list(le.classes_)
    cm = confusion_matrix(y_true, y_pred, labels=list(range(len(classes))))
    analysis = analyze_confusion_matrix(cm, classes)

    prec, rec, f1, support = precision_recall_fscore_support(
        y_true, y_pred, labels=list(range(len(classes))), zero_division=0
    )
    metrics_df = pd.DataFrame(
        {
            "Class": classes,
            "Precision": np.round(prec, 4),
            "Recall": np.round(rec, 4),
            "F1": np.round(f1, 4),
            "Support": support.astype(int),
        }
    )

    lines: list[str] = []
    lines.append("# InferAI — Confusion Matrix Analysis\n\n")
    lines.append(
        "Automated analysis of misclassification patterns on `dataset/test_set.csv`. "
        "Generated by `reports/generate_confusion_matrix_analysis.py`.\n\n"
    )

    lines.append("## Confusion matrix (counts)\n\n")
    cm_df = pd.DataFrame(cm, index=classes, columns=classes)
    cm_df.index.name = "True \\ Pred"
    lines.append(dataframe_to_markdown(cm_df.reset_index(), index=False) + "\n\n")

    lines.append("## Key findings\n\n")

    mc = analysis["most_confused"]
    lc = analysis["least_confused"]
    lo = analysis["lowest_recall"]
    hi = analysis["highest_recall"]

    if mc:
        expl = _pair_explanation(mc["true"], mc["predicted"])
        lines.append(
            f"- **Most confused class pair:** {mc['true']} → {mc['predicted']} "
            f"({mc['count']} errors, {mc['rate_of_true_class']:.1%} of true {mc['true']} examples). "
            f"This suggests overlap between {expl}\n"
        )
    if lc and lc != mc:
        lines.append(
            f"- **Least confused off-diagonal pair:** {lc['true']} → {lc['predicted']} "
            f"({lc['count']} error(s)).\n"
        )
    lines.append(
        f"- **Highest recall class:** {hi['class']} ({hi['recall']:.1%} recall, n={hi['support']}).\n"
    )
    lines.append(
        f"- **Lowest recall class:** {lo['class']} ({lo['recall']:.1%} recall, n={lo['support']}).\n"
    )

    lines.append("\n## Human-readable summary\n\n")
    if mc:
        lines.append(
            f"Most errors occurred between **{mc['true']}** and **{mc['predicted']}**, "
            f"suggesting {_pair_explanation(mc['true'], mc['predicted'])} "
            f"The model achieves strongest retrieval on **{hi['class']}** but struggles most "
            f"to recover **{lo['class']}** examples, which is consistent with overlapping lexical "
            "cues in short argumentative spans.\n\n"
        )

    lines.append("## Top off-diagonal confusions\n\n")
    if analysis["off_diag"]:
        top_df = pd.DataFrame(analysis["off_diag"][:8]).rename(
            columns={
                "true": "True class",
                "predicted": "Predicted class",
                "count": "Count",
                "rate_of_true_class": "Rate (of true class)",
            }
        )
        top_df["Rate (of true class)"] = top_df["Rate (of true class)"].map(
            lambda x: f"{x:.1%}"
        )
        lines.append(dataframe_to_markdown(top_df) + "\n\n")
    else:
        lines.append("_No off-diagonal errors._\n\n")

    lines.append("## Per-class recall context\n\n")
    lines.append(dataframe_to_markdown(metrics_df) + "\n")

    out = _ROOT / "reports" / "confusion_matrix_analysis.md"
    out.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
